# Generated by Django 2.0.8 on 2018-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180819_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Mail'), ('female', 'Female'), ('not-specified', 'Not Specified')], max_length=80, null=True),
        ),
    ]
