# Generated by Django 2.0.8 on 2018-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180819_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('female', 'Female'), ('male', 'Mail')], max_length=80, null=True),
        ),
    ]
