# Generated by Django 2.0.8 on 2018-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180819_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Mail'), ('not-specified', 'Not Specified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
