# Generated by Django 2.0.8 on 2018-09-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180901_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('male', 'Mail'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
